config/routes.rb
Rails.application.routes.draw do
  resources :pokemon, only: [:index, :show]
  get "items/index"
  get "items/:id", to: "items#show", as: :item
  get "moves/index"
  get "moves/:id", to: "moves#show", as: :move
  get "abilities/index"
  get "abilities/:id", to: "abilities#show", as: :ability
  root "home#index"
  get "/about", to: "static_pages#about"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :pokemon_abilities
  has_many :pokemons, through: :pokemon_abilities

  validates :name, presence: true, uniqueness: true
  validates :name, length: { maximum: 50 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :pokemon_items
  has_many :pokemons, through: :pokemon_items

  validates :name, presence: true, uniqueness: true
  validates :cost, numericality: { greater_than_or_equal_to: 0 }
end

app/models/move.rb
class Move < ApplicationRecord
  has_many :pokemon_moves
  has_many :pokemons, through: :pokemon_moves

  validates :name, presence: true, uniqueness: true
  validates :pp, numericality: { only_integer: true, greater_than: 0 }
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokemon_abilities
  has_many :abilities, through: :pokemon_abilities

  has_many :pokemon_moves
  has_many :moves, through: :pokemon_moves

  has_many :pokemon_items
  has_many :items, through: :pokemon_items

  validates :name, presence: true, uniqueness: true
  validates :type1, presence: true
end

app/models/pokemon_ability.rb
class PokemonAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability
end

app/models/pokemon_item.rb
class PokemonItem < ApplicationRecord
  belongs_to :pokemon
  belongs_to :item
end

app/models/pokemon_move.rb
class PokemonMove < ApplicationRecord
  belongs_to :pokemon
  belongs_to :move
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  def index
    @abilities = Ability.order(:name).page(params[:page]).per(10)
    @total = Ability.count
  end

  def show
    @ability = Ability.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @abilities = Ability.order(:name)
    @items = Item.order(:name)
    @moves = Move.order(:name)

    @pokemons = Pokemon.all

    keyword = params[:keyword].to_s.strip
    if keyword.present?
      @pokemons = @pokemons.where('name ILIKE ?', "%#{keyword}%")
    end

    if params[:ability_id].present?
      @pokemons = @pokemons.joins(:abilities).where(abilities: { id: params[:ability_id] })
    end

    if params[:item_id].present?
      @pokemons = @pokemons.joins(:items).where(items: { id: params[:item_id] })
    end

    if params[:move_id].present?
      @pokemons = @pokemons.joins(:moves).where(moves: { id: params[:move_id] })
    end

    @total = @pokemons.count

    @pokemons = @pokemons.distinct.order(:id).page(params[:page]).per(10)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.order(:name).page(params[:page]).per(10)
    @total = Item.count
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def index
    @moves = Move.order(:name).page(params[:page]).per(10)
    @total = Move.count
  end

  def show
    @move = Move.find(params[:id])
  end
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  def show
    @pokemon = Pokemon.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/components_helper.rb
require "tailwind_merge"

module ComponentsHelper
  def tw(*classes)
    TailwindMerge::Merger.new.merge(classes.join(" "))
  end

  PRIMARY_CLASSES = " bg-primary text-primary-foreground hover:bg-primary/80 "
  SECONDARY_CLASSES = " bg-secondary text-secondary-foreground hover:bg-secondary/80 "
  OUTLINE_CLASSES = "  border border-input bg-background hover:bg-accent hover:text-accent-foreground "
  GHOST_CLASSES = " hover:bg-accent hover:text-accent-foreground  "
  DESTRUCTIVE_CLASSES = " bg-destructive text-destructive-foreground hover:bg-destructive/90 "

  module Button
    PRIMARY = ComponentsHelper::PRIMARY_CLASSES
    SECONDARY = ComponentsHelper::SECONDARY_CLASSES
    OUTLINE = ComponentsHelper::OUTLINE_CLASSES
    GHOST = ComponentsHelper::GHOST_CLASSES
    DESTRUCTIVE = ComponentsHelper::DESTRUCTIVE_CLASSES
  end

  module Alert
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/abilities/index.html.erb
<section class="mt-12 w-full">
  <h1 class="mb-8 text-2xl font-bold tracking-tight text-gray-900 sm:text-6xl">Abilities</h1>
  <div class="mb-8"><%= @total %> abilities found</div>
  <!-- abilities list -->
  <% if @abilities.any? %>
    <!-- table head -->
    <div class="mb-4 w-full grid grid-cols-2 font-semibold border-b border-gray-300 py-2">
      <div>ID</div>
      <div>Name</div>
    </div>
    <!-- table content -->
    <div class="grid gap-4">
      <% @abilities.each do |ability| %>
        <div class="w-full grid grid-cols-2 items-center border-b border-gray-200 py-2">
          <div><%= ability.id %></div>
          <div><%= link_to ability.name, ability_path(ability), class: "text-blue-500 hover:underline" %></div>
        </div>
      <% end %>
    </div>
    <!-- pagination -->
    <div class="mt-12 mb-24">
      <%= render 'kaminari/paginator', collection: @abilities %>
    </div>
  <% else %>
    <p>No abilities found.</p>
  <% end %>
</section>

app/views/abilities/show.html.erb
<section class="mt-12 w-full">
  <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-6xl"><%= @ability.name %></h1>
  <% if @ability.present? %>
    <!-- Ability Details -->
    <div class="mt-12">
      <p><strong>ID:</strong> <%= @ability.id %></p>
      <p><strong>Name:</strong> <%= @ability.name %></p>
    </div>

    <!-- Pokémon with this Ability -->
    <div class="mt-12">
      <h2 class="text-xl font-semibold text-gray-800">Pokémon with this Ability</h2>

      <% if @ability.pokemons.any? %>
        <%= render "shared/pokemon_list", pokemons: @ability.pokemons %>
      <% else %>
        <p class="text-gray-600 mt-4">No Pokémon has this ability.</p>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-600">Ability not found.</p>
  <% end %>
</section>

app/views/items/index.html.erb
<section class="mt-12">
  <h1 class="mb-8 text-2xl font-bold tracking-tight text-gray-900 sm:text-6xl">Items</h1>
  <div class="mb-8"><%= @total %> items found</div>
  <!-- abilities list -->
  <% if @items.any? %>
    <!-- table head -->
    <div class="mb-4 w-full grid grid-cols-4 font-semibold border-b border-gray-300 py-2">
      <div>ID</div>
      <div>Name</div>
      <div>Cost</div>
      <div>Fling Power</div>
    </div>
    <!-- table content -->
    <div class="grid gap-4">
      <% @items.each do |item| %>
        <div class="w-full grid grid-cols-4 items-center border-b border-gray-200 py-2">
          <div><%= item.id %></div>
          <div><%= link_to item.name, item_path(item), class: "text-blue-500 hover:underline" %></div>
          <div><%= item.cost %></div>
          <div><%= item.fling_power %></div>
        </div>
      <% end %>
    </div>
    <!-- pagination -->
    <div class="mt-12 mb-24">
      <%= render 'kaminari/paginator', collection: @items %>
    </div>
  <% else %>
    <p>No items found.</p>
  <% end %>
</section>

app/views/items/show.html.erb
<section class="mt-12 w-full">
  <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-6xl"><%= @item.name %></h1>
  <% if @item.present? %>
    <!-- Ability Details -->
    <div class="mt-12">
      <p><strong>ID:</strong> <%= @item.id %></p>
      <p><strong>Name:</strong> <%= @item.name %></p>
    </div>

    <!-- Pokémon with this Ability -->
    <div class="mt-12">
      <h2 class="text-xl font-semibold text-gray-800">Pokémon who holds this item:</h2>

      <% if @item.pokemons.any? %>
        <%= render "shared/pokemon_list", pokemons: @item.pokemons %>
      <% else %>
        <p class="text-gray-600 mt-4">No Pokémon has this item.</p>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-600">Item not found.</p>
  <% end %>
</section>

app/views/moves/index.html.erb
<section class="mt-12 w-full">
  <h1 class="mb-8 text-2xl font-bold tracking-tight text-gray-900 sm:text-6xl">Moves</h1>
  <div class="mb-8"><%= @total %> moves found</div>
  <!-- abilities list -->
  <% if @moves.any? %>
    <!-- table head -->
    <div class="mt-4 w-full grid grid-cols-5 font-semibold border-b border-gray-300 py-2">
      <div>ID</div>
      <div>Name</div>
      <div>PP</div>
      <div>Priority</div>
      <div>Move Type</div>
    </div>
    <!-- table content -->
    <div class="grid gap-4 mt-4">
      <% @moves.each do |move| %>
        <div class="w-full grid grid-cols-5 items-center border-b border-gray-200 py-2">
          <div><%= move.id %></div>
          <div><%= link_to move.name, move_path(move), class: "text-blue-500 hover:underline" %></div>
          <div><%= move.pp %></div>
          <div><%= move.priority %></div>
          <div><%= move.move_type %></div>
        </div>
      <% end %>
    </div>
    <!-- pagination -->
    <div class="mt-12 mb-24">
      <%= render 'kaminari/paginator', collection: @moves %>
    </div>
  <% else %>
    <p>No moves found.</p>
  <% end %>
</section>

app/views/moves/show.html.erb
<section class="mt-12 w-full">
  <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-6xl"><%= @move.name %></h1>
  <% if @move.present? %>
    <!-- Ability Details -->
    <div class="mt-12">
      <p><strong>ID:</strong> <%= @move.id %></p>
      <p><strong>Name:</strong> <%= @move.name %></p>
      <p><strong>PP:</strong> <%= @move.pp %></p>
      <p><strong>Priority:</strong> <%= @move.priority %></p>
      <p><strong>Move Type:</strong> <%= @move.move_type %></p>
    </div>

    <!-- Pokémon with this Ability -->
    <div class="mt-12">
      <h2 class="text-xl font-semibold text-gray-800">Pokémon who can make this move:</h2>

      <% if @move.pokemons.any? %>
        <%= render "shared/pokemon_list", pokemons: @move.pokemons %>
      <% else %>
        <p class="text-gray-600 mt-4">No Pokémon can make this move.</p>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-600">Move not found.</p>
  <% end %>
</section>

app/views/pokemon/show.html.erb
<section class="mt-12 w-full">
  <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-6xl"><%= @pokemon.name %></h1>
  <% if @pokemon.present? %>
    <!-- Pokemon Details -->
    <div class="mt-12">
      <p><strong>ID:</strong> <%= @pokemon.id %></p>
      <p><strong>Name:</strong> <%= @pokemon.name %></p>
      <p><strong>Base Experience:</strong> <%= @pokemon.base_experience %></p>
      <p><strong>Height:</strong> <%= @pokemon.height %></p>
      <p><strong>Weight:</strong> <%= @pokemon.weight %></p>
      <p><strong>Default State:</strong> <%= @pokemon.is_default %></p>
      <p><strong>Order:</strong> <%= @pokemon.order_num %></p>
      <p><strong>Primary Type:</strong> <%= @pokemon.type1 %></p>
      <p><strong>Secondary Type:</strong> <%= @pokemon.type2 %></p>
    </div>

    <!-- Pokémon's Items -->
    <div class="mt-12">
      <h2 class="text-xl font-semibold text-gray-800"><%= @pokemon.name %>'s Items</h2>

      <% if @pokemon.items.any? %>
        <!-- table head -->
        <div class="mb-4 w-full grid grid-cols-4 font-semibold border-b border-gray-300 py-2">
          <div>ID</div>
          <div>Name</div>
          <div>Cost</div>
          <div>Fling Power</div>
        </div>
        <!-- table content -->
        <ul class="grid gap-4">
          <% @pokemon.items.each do |item| %>
            <div class="w-full grid grid-cols-4 items-center border-b border-gray-200 py-2">
              <div><%= item.id %></div>
              <div><%= link_to item.name, item_path(item), class: "text-blue-500 hover:underline" %></div>
              <div><%= item.cost %></div>
              <div><%= item.fling_power %></div>
            </div>
          <% end %>
        </ul>
      <% else %>
        <p class="text-gray-600 mt-4"><%= @pokemon.name %> doesn't have any items.</p>
      <% end %>
    </div>

    <!-- Pokémon's Abilities -->
    <div class="mt-12">
      <h2 class="text-xl font-semibold text-gray-800"><%= @pokemon.name %>'s Abilities</h2>

      <% if @pokemon.abilities.any? %>
        <!-- table head -->
        <div class="mt-4 w-full grid grid-cols-2 font-semibold border-b border-gray-300 py-2">
          <div>ID</div>
          <div>Name</div>
        </div>
        <ul class="grid gap-4 mt-4">
          <% @pokemon.abilities.each do |ability| %>
            <li class="w-full grid grid-cols-2 items-center border-b border-gray-200 py-2">
              <div><%= ability.id %></div>
              <div><%= link_to ability.name, ability_path(ability), class: "text-blue-500 hover:underline" %></div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="text-gray-600 mt-4"><%= @pokemon.name %> doesn't have any abilities.</p>
      <% end %>
    </div>

    <!-- Pokémon's Moves -->
    <div class="mt-12">
      <h2 class="text-xl font-semibold text-gray-800"><%= @pokemon.name %>'s Moves</h2>

      <% if @pokemon.moves.any? %>
        <!-- table head -->
        <div class="mt-4 w-full grid grid-cols-5 font-semibold border-b border-gray-300 py-2">
          <div>ID</div>
          <div>Name</div>
          <div>PP</div>
          <div>Priority</div>
          <div>Move Type</div>
        </div>
        <!-- table content -->
        <ul class="grid gap-4 mt-4">
          <% @pokemon.moves.each do |move| %>
            <div class="w-full grid grid-cols-5 items-center border-b border-gray-200 py-2">
              <div><%= move.id %></div>
              <div><%= link_to move.name, move_path(move), class: "text-blue-500 hover:underline" %></div>
              <div><%= move.pp %></div>
              <div><%= move.priority %></div>
              <div><%= move.move_type %></div>
            </div>
          <% end %>
        </ul>
      <% else %>
        <p class="text-gray-600 mt-4"><%= @pokemon.name %> doesn't have any moves.</p>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-600">Pokémon <%= @pokemon.name %> not found.</p>
  <% end %>
</section>